# Site settings
title: Mariya Messerli
email: mariya@messerli.ch
description: >- # this means to ignore newlines until "baseurl:"
  Investment professional with expertise in insurance, technology, and global markets.
  Focused on fundamental analysis and long-term value creation.
baseurl: "/minimal" # the subpath of your site, e.g. /blog
url: "https://stefsabi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/